import pytest


@pytest.fixture
def test_salary_dict() -> dict:
    return {
        "from": 270000,
        "to": 300000,
        "currency": "RUR",
        "gross": False,
        "mode": {"id": "MONTH", "name": "За месяц"},
    }


@pytest.fixture
def test_vacancy_dict() -> dict:
    return {
        "id": "128514207",
        "name": "PHP-разработчик",
        "area": {"id": "4", "name": "Новосибирск", "url": "https://api.hh.ru/areas/4"},
        "salary": {"from": 270000, "to": None, "currency": "RUR", "gross": False},
        "salary_range": {
            "from": 270000,
            "to": None,
            "currency": "RUR",
            "gross": False,
            "mode": {"id": "MONTH", "name": "За месяц"},
            "frequency": {"id": "TWICE_PER_MONTH", "name": "Два раза в месяц"},
        },
        "type": {"id": "open", "name": "Открытая"},
        "address": {
            "city": "Новосибирск",
            "street": "Советская улица",
            "building": "64",
            "lat": 55.048513,
            "lng": 82.911482,
            "raw": "Новосибирск, Советская улица, 64",
            "metro": {
                "station_name": "Гагаринская",
                "line_name": "Ленинская",
                "station_id": "52.295",
                "line_id": "52",
                "lat": 55.051071,
                "lng": 82.91477,
            },
            "metro_stations": [
                {
                    "station_name": "Гагаринская",
                    "line_name": "Ленинская",
                    "station_id": "52.295",
                    "line_id": "52",
                    "lat": 55.051071,
                    "lng": 82.91477,
                }
            ],
            "id": "6742717",
        },
        "published_at": "2026-02-01T08:55:32+0300",
        "created_at": "2026-02-01T08:55:32+0300",
        "url": "https://api.hh.ru/vacancies/128514207?host=hh.ru",
        "alternate_url": "https://hh.ru/vacancy/128514207",
        "relations": [],
        "employer": {
            "id": "5832652",
            "name": "Токидоки",
            "url": "https://api.hh.ru/employers/5832652",
            "alternate_url": "https://hh.ru/employer/5832652",
            "logo_urls": {
                "original": "https://img.hhcdn.ru/employer-logo-original-round/6341088.png",
                "90": "https://img.hhcdn.ru/employer-logo-round/6341090.png",
                "240": "https://img.hhcdn.ru/employer-logo-round/6341091.png",
            },
            "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5832652",
            "country_id": 1,
        },
        "snippet": {
            "requirement": "знание современных фреймворков (Symfony или Laravel).",
            "responsibility": "поддержка и доработка сайта компании (японские и корейские автомобильные аукционы).",
        },
        "contacts": None,
        "schedule": {"id": "remote", "name": "Удаленная работа"},
        "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
    }


@pytest.fixture
def test_other_vacancy_dict() -> dict:
    return {
        "id": "3333",
        "name": "Работник",
        "area": {"id": "1", "name": "Россия"},
        "salary": {"from": 270000, "currency": "RUR", "gross": False},
        "created_at": None,
        "employer": {},
        "alternate_url": "https://hh.ru/vacancy/128514207",
        "salary_range": {
            "from": 270000,
            "currency": "RUR",
            "mode": {"name": "За месяц"},
        },
    }


@pytest.fixture
def parsed_vacancy_dict() -> dict:

    return {
        "hh_id": "128514207",
        "name": "PHP-разработчик",
        "vacancy_link": "https://hh.ru/vacancy/128514207",
        "amount_from": 270000,
        "amount_to": None,
        "currency": "RUB",
        "mode": "За месяц",
        "converted_from": 270000,
        "converted_to": None,
        "required_currency": "RUB",
        "location": "Новосибирск",
        "created_at": "2026-02-01T08:55:32+0300",
        "employer_name": "Токидоки",
        "employer_link": "https://hh.ru/employer/5832652",
        "requirements": "знание современных фреймворков (Symfony или Laravel).",
        "responsibility": "поддержка и доработка сайта компании (японские и корейские автомобильные аукционы).",
    }


@pytest.fixture
def area_codes() -> dict:
    return {
        "россия": {
            "id": 113,
            "regions": {
                "республика марий эл": {
                    "id": 1620,
                    "cities": {
                        "виловатово": 4228,
                        "волжск": 1621,
                        "звенигово": 1622,
                        "знаменский": 4229,
                        "йошкар-ола": 61,
                        "кельмаксола": 4230,
                        "килемары": 4231,
                        "козьмодемьянск": 1623,
                        "красногорский (республика марий эл)": 4232,
                    },
                },
                "москва": {"id": 1, "cities": {}},
                "московская область": {
                    "id": 2019,
                    "cities": {
                        "авсюнино (московская область)": 5976,
                        "автополигон (дмитровский городской округ, московская область)": 144,
                        "александровка (московская область)": 11255,
                        "алпатьево (московская область)": 8190,
                        "алфертищево (московская область)": 11249,
                        "алфимово (московская область)": 8220,
                        "андреевка (московская область)": 6339,
                        "архангельское (московская область)": 8229,
                        "астапово (московская область)": 8181,
                        "ашукино (московская область)": 5968,
                        "балашиха (московская область)": 2020,
                    },
                },
            },
        },
        "беларусь": {
            "id": 16,
            "regions": {
                "брест": {"id": 1007, "cities": {}},
                "брестская область": {
                    "id": 2233,
                    "cities": {
                        "антополь": 11130,
                        "барановичи": 2239,
                        "белоозерск": 2630,
                        "береза": 2240,
                        "большие лепесы": 11861,
                        "большие мотыкалы": 11875,
                        "вишевичи": 11137,
                        "высокое": 2590,
                        "галево": 11135,
                        "ганцевичи": 2241,
                        "давид-городок": 2741,
                        "домачево": 11872,
                    },
                },
            },
        },
        "грузия": {
            "id": 28,
            "regions": {
                "ахалцихе": {"id": 2820, "cities": {}},
                "батуми": {"id": 2814, "cities": {}},
                "болниси": {"id": 2821, "cities": {}},
                "боржоми": {"id": 2822, "cities": {}},
            },
        },
        "узбекистан": {
            "id": 97,
            "regions": {
                "аккурган": {"id": 2763, "cities": {}},
                "акташ (узбекистан)": {"id": 2764, "cities": {}},
                "алат (узбекистан)": {"id": 2765, "cities": {}},
                "алмалык": {"id": 2766, "cities": {}},
                "ангрен": {"id": 2767, "cities": {}},
                "андижан": {"id": 2768, "cities": {}},
                "асака": {"id": 2769, "cities": {}},
                "ташкент": {"id": 2759, "cities": {}},
            },
        },
        "казахстан": {
            "id": 40,
            "regions": {
                "актобе": {"id": 154, "cities": {}},
                "алатау": {"id": 11524, "cities": {}},
                "алматы": {"id": 160, "cities": {}},
                "алтай (зыряновск)": {"id": 169, "cities": {}},
                "астана": {"id": 159, "cities": {}},
                "байконур (кызылорд. обл)": {"id": 2226, "cities": {}},
                "иртышск": {"id": 11332, "cities": {}},
                "караганда": {"id": 177, "cities": {}},
                "костанай": {"id": 172, "cities": {}},
            },
        },
        "другие регионы": {
            "id": 1001,
            "regions": {
                "абхазия": {"id": 2112, "cities": {}},
                "австралия": {"id": 6, "cities": {}},
                "молдова": {
                    "id": 62,
                    "cities": {
                        "бендеры": 11481,
                        "кишинёв": 5049,
                        "комрат": 11482,
                        "тирасполь": 11285,
                        "единец": 11483,
                    },
                },
            },
        },
    }


@pytest.fixture
def saved_vacancies_data() -> list:
    return [
        {
            "hh_id": "130660306",
            "name": "Повар горячего цеха",
            "vacancy_link": "https://hh.ru/vacancy/130660306",
            "location": "Алматы",
            "created_at": "2026-02-22T09:18:06+0300",
            "employer_name": "Syrniki BT",
            "employer_link": "https://hh.ru/employer/10554365",
            "requirements": "Обязательно наличие диплома повара. \u200d Опыт работы обязателен. Ответственный",
            "responsibility": None,
            "amount_from": 1000000,
            "amount_to": 1200000,
            "currency": "KZT",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130467116",
            "name": "Охранник",
            "vacancy_link": "https://hh.ru/vacancy/130467116",
            "location": "Ташкент",
            "created_at": "2026-02-16T09:15:41+0300",
            "employer_name": "Afrosiyob",
            "employer_link": "https://hh.ru/employer/5489428",
            "requirements": "Опыт работы в данной сфере не менее 3 лет. Пунктуальность. Внимательность.",
            "responsibility": "Обеспечение порядка на вверенной территории. Пресечение краж",
            "amount_from": 6500000,
            "amount_to": None,
            "currency": "UZS",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130573247",
            "name": "Главный бухгалтер в единственном лице",
            "vacancy_link": "https://hh.ru/vacancy/130573247",
            "location": "Астана",
            "created_at": "2026-02-18T14:57:32+0300",
            "employer_name": "ВИЗАМЕТРИК",
            "employer_link": "https://hh.ru/employer/1580604",
            "requirements": "Высшее экономическое образование и/или доп. образование в области бухгалтерского учета.",
            "responsibility": "Полное ведение кадрового, бухгалтерского, налогового учета компании.",
            "amount_from": 1600000,
            "amount_to": None,
            "currency": "KZT",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130543586",
            "name": "Водитель",
            "vacancy_link": "https://hh.ru/vacancy/130543586",
            "location": "Ташкент",
            "created_at": "2026-02-17T20:02:18+0300",
            "employer_name": "MAXSUS FORCE ALLIANCE",
            "employer_link": "https://hh.ru/employer/12291710",
            "requirements": "Стаж не менее 10 лет. Категория В (наличие С категории приветствуется).",
            "responsibility": "Личный водитель (семейный). Функции водителя.",
            "amount_from": 5000000,
            "amount_to": 7000000,
            "currency": "UZS",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130646930",
            "name": "Водитель",
            "vacancy_link": "https://hh.ru/vacancy/130646930",
            "location": "Астана",
            "created_at": "2026-02-20T15:06:57+0300",
            "employer_name": "ГУ Генеральная Прокуратура Республики Казахстан",
            "employer_link": "https://hh.ru/employer/12623852",
            "requirements": "Проживание на левом берегу. Опыт работы. Знание города. Аккуратное вождение.",
            "responsibility": "Возить руководителя.",
            "amount_from": 100000,
            "amount_to": 200000,
            "currency": "KZT",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130620371",
            "name": "Курьер с аптек, канцелярии и документов (легкие-короткие посылки и заказы весом до 2-3 кг)",
            "vacancy_link": "https://hh.ru/vacancy/130620371",
            "location": "Россия",
            "created_at": "2026-02-19T17:55:40+0300",
            "employer_name": "Яндекс.Еда",
            "employer_link": "https://hh.ru/employer/9694561",
            "requirements": None,
            "responsibility": "Доставляйте заказы.  Оставьте заявку.  Приступайте к доставке",
            "amount_from": 0.0,
            "amount_to": 190000,
            "currency": "RUB",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130544536",
            "name": "Администратор",
            "vacancy_link": "https://hh.ru/vacancy/130544536",
            "location": "Мозырь",
            "created_at": "2026-02-17T22:41:18+0300",
            "employer_name": "Смайл Клиник",
            "employer_link": "https://hh.ru/employer/10952595",
            "requirements": "Коммуникабельность. Ответственность. Желание работать в коллективе. Желание обучаться.",
            "responsibility": "Отвечать на звонки. Формировать приемы. Расчет пациентов. Работа в регистратуре.",
            "amount_from": 1200,
            "amount_to": None,
            "currency": "BYR",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "129915513",
            "name": "Менеджер маркетплейсов Kaspi, офлайн",
            "vacancy_link": "https://hh.ru/vacancy/129915513",
            "location": "Костанай",
            "created_at": "2026-01-27T12:33:34+0300",
            "employer_name": "TOP100KROSS",
            "employer_link": "https://hh.ru/employer/5547195",
            "requirements": "Обязательный опыт работы с Kaspi-магазином. С каким Kaspi-магазином работали.",
            "responsibility": "Размещение и оптимизация товаров на Kaspi. Оформление карточек товаров.",
            "amount_from": 8000,
            "amount_to": 10000,
            "currency": "KZT",
            "mode": "За смену",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130153084",
            "name": "Стажёр / начинающий специалист 1С",
            "vacancy_link": "https://hh.ru/vacancy/130153084",
            "location": "Ташкент",
            "created_at": "2026-02-04T09:48:06+0300",
            "employer_name": "AIVA INVEST",
            "employer_link": "https://hh.ru/employer/11678149",
            "requirements": "Готовиться к официальной сертификации 1С. - Знание русского и узбекского языков.",
            "responsibility": "1С: Бухгалтерия. - 1С: Управление компанией. - Разработка на платформе 1С.",
            "amount_from": 6000000,
            "amount_to": None,
            "currency": "UZS",
            "mode": "За месяц",
            "converted_from": 0.0,
            "converted_to": None,
            "required_currency": None,
        },
        {
            "hh_id": "130100999",
            "name": "Агент по обслуживанию пассажиров в Аэропорт Ташкента",
            "vacancy_link": "https://hh.ru/vacancy/130100999",
            "location": "Ташкент",
            "created_at": "2026-02-02T16:52:12+0300",
            "employer_name": "SKYSERV PRO MMC",
            "employer_link": "https://hh.ru/employer/12452768",
            "requirements": "Образование: средне-специальное, высшее оконченное.",
            "responsibility": "ОПИСАНИЕ РАБОТЫ. Приветствие и регистрация пассажиров бизнес-зала.",
        },
    ]
